# Julia01_intro

## Installing packages

Packages can be easily installed from the REPL. Let’s install, for example, the Linear Algebra package. Simply do:

In [6]:
import Pkg; Pkg.add("LinearAlgebra")

#install package

   Resolving package versions...
  No Changes to `~/.julia/environments/v1.7/Project.toml`
  No Changes to `~/.julia/environments/v1.7/Manifest.toml`


In [ ]:
using Pkg; Pkg.add("LinearAlgebra")

#this is another way to install package

For using the packages in our projects, we need to include them with a using statement:

In [5]:
using LinearAlgebra

#call package

在Julia中，下載package的快捷鍵是 `]` 

則只要接著輸入： `add "package_name"` 即可

Press backspace when you are done with installing packages.

## Basic Variable Type

In [47]:
a=1+1
typeof(a)

Int64

In [48]:
a="Hello"
typeof(a)

String

### Conversion of Integer to Float

We can convert an integers to floats with different kinds of precisions, using functions like `Float64`, `Float32` and `Float16` which correspond to double, single, and half precision numbers.

In [52]:
Float64(2) # double precision

2.0

In [53]:
Float32(2) # single-precision

2.0f0

In [54]:
Float16(2) # half-precision

Float16(2.0)

### Conversion of Float to Integer

In [55]:
Int64(2.0)

2

In [56]:
Int64(2.4)

LoadError: InexactError: Int64(2.4)

In [57]:
floor(Int64,2.4)

2

In [58]:
ceil(Int64,2.4)

3

In [59]:
round(Int64,2.4)

2

### Integer Division

By default, dividing two integers could return a float.

If we are interested in the integer (or Euclidean) division, 

the div function (or ÷, whose Unicode symbol can be obtained with \div) returns the quotient, 

while for the remainder we have the rem function, or %.



In [61]:
a=1/2

0.5

`div(x,y)`  x/y, truncated to an integer.

In [63]:
div(10,3) #取商

3

In [66]:
÷(10,3) #取商

3

`rem(x,y)` computes the remainder of x/y

In [67]:
rem(10,3) #取餘

1

In [68]:
10%3

1

### Integer vs Float

In [69]:
a=2

2

In [70]:
typeof(a)  #getting an Int64 by default.

Int64

In [71]:
a=1/2^64

Inf

In [72]:
2^64

0

Two things just happened. 

In the first place, an Int64 will overflow past 2^{64}, 

and the default overflow value is 0.

In [73]:
1/2.0^64

5.421010862427522e-20

In [74]:
(1/2)^64

5.421010862427522e-20

In [75]:
1.0/2^64

Inf

### Logical Operators

- not: `!`
- and: `&&`
- or:  `||`

Importantly, `&&` and `||` are **short-circuited**

In [ ]:
if a>0 && expensive_computation(b)>0
    do_something()
end

In this way, we avoid performing the expensive computation 

if it’s not necessary (when a>0 returns false).

`||` is **short-circuited** means that you won’t get a nasty error when doing something like

In [ ]:
if @isdefined(ge) && ge>0
    print("ge exists and is greater than 0")
end

because trying to assess whether an undefined variable is greater than zero is usually not permitted in any programming language. 

If the variable is not defined, the second condition won’t be checked.

As for the `or` operator, the fact that it is **short-circuited** means that it will return true 

if the first expression is true without the need to evaluate the second expression. 

This can also lead to performance gains.

In [ ]:
if 3 > 2 || expensive_computation(b) > 0
    do_something()
end

The `expensive_computation` function won’t be called, as the first expression returnes true.

### Logical to Number

In Julia, `Bool` is a subtype of `Integer`. 

`true` equals 1, while `false` equals zero. 

In particular, we can do numerical operations on `Bool` types without the need of any type conversion.

In [78]:
true+true

2

### Strings and Chars

`Strings` are initialized with `"` 
while `chars` use `'`.

In [79]:
"Hello" #string

"Hello"

In [80]:
'H' #char

'H': ASCII/Unicode U+0048 (category Lu: Letter, uppercase)

In [81]:
'Hello' # error!

LoadError: syntax: character literal contains multiple characters

### Concatenate Strings

you can use the `*` operator and the `string` function.

In [82]:
"Hello " * "wor" * "id"

"Hello worid"

In [83]:
string("Hello ", " ","world")

"Hello  world"

### Convert Number to String

- using the `string` function.
- using string interpolation.
- using the classic C-style `Printf` package to format the output.

In [84]:
string(1/7)

"0.14285714285714285"

In [85]:
"$(1/7)"

"0.14285714285714285"

In [98]:
using Pkg; Pkg.add("Printf")

   Resolving package versions...
  No Changes to `~/.julia/environments/v1.7/Project.toml`
  No Changes to `~/.julia/environments/v1.7/Manifest.toml`


In [95]:
using Printf

In [104]:
@sprintf("%6.4f",1/7)

"0.1429"

### Concatenate a number to a string



- Using the string function

In [100]:
string("In ancient Babylon they approximated pi to 25/8, which is ", 25/8)

"In ancient Babylon they approximated pi to 25/8, which is 3.125"

- Using string interpolation

In [101]:
"In ancient Babylon they approximated pi to 25/8, which is $(25/8)"


"In ancient Babylon they approximated pi to 25/8, which is 3.125"

With string interpolation, 

the expression between parenthesis we’ll be evaluated (which in this case returns a Float), 

and then converted to a string.

In [102]:
rmse = 1.5; mse = 1.1; R2 = 0.94
"Our model has a R^2 of $(R2), rmse of $(rmse), and mse of $(mse)"

"Our model has a R^2 of 0.94, rmse of 1.5, and mse of 1.1"

- Using the Printf package

In case you need to control the number of digits in the output, 

or use scientific notation, 

you can use the classic, C-style, Printf package, 

which contains the `@sprintf` macro that returns a string.

In [103]:
using Printf
str = @sprintf("Archimedes approximated pi to 22/7, which is %.4f...", 22/7)


"Archimedes approximated pi to 22/7, which is 3.1429..."

|format|description       |example  |
|-----|-----------------|--------|
|%.4f  |4 decimal digits  |100.1429 |
|%.4e  |Scientific notation with 4 digits|1.4286e-05|

## For loops

### Simple For Loop

In [ ]:
for iterator in range
    execute_statements(iterator)
end

In [10]:
## evaluate the sum of the first 100,000 terms of the quadratic series.

x=0
for k in 1:100000   # 1+2+3+4+...+100000
    x=x+(1/k)^2
end

x

1.6449240668982423

In [9]:
x=0
for k in 1:10:100000   # 1+11+21+31+...+100000
    x=x+(1/k)^2
end

x

1.0143319914679227

### Nested For Loops

In [12]:
for i in 1:3
    for j in 1:3
        print("i=", i, " j=", j, "\n")
    end
end

i=1 j=1
i=1 j=2
i=1 j=3
i=2 j=1
i=2 j=2
i=2 j=3
i=3 j=1
i=3 j=2
i=3 j=3


In [13]:
for i in 1:3, j in 1:3
    print("i=", i, " j=", j,"\n")
end

i=1 j=1
i=1 j=2
i=1 j=3
i=2 j=1
i=2 j=2
i=2 j=3
i=3 j=1
i=3 j=2
i=3 j=3


Click [Here](https://docs.julialang.org/en/v1/manual/unicode-input/) to check Julia unicode symbols.

In [ ]:
Press \in + tab to get ∈
Press \pi + tab to get π
Press \alpha + tab to get α
Press \beta + tab to get β
Press \lambda + tab to get λ

In [14]:
for i ∈ 1:3, j ∈ 1:3
    print("i=", i, " j=", j, "\n")
end

i=1 j=1
i=1 j=2
i=1 j=3
i=2 j=1
i=2 j=2
i=2 j=3
i=3 j=1
i=3 j=2
i=3 j=3


### Break and Continue Statement

we could interrupt the computations

if some convergence criteria is met.



In [107]:
x=0
for k in 1:100000
    term=(1/k)^2
    x=x+term
    if (abs(term)< 1e-10) break end
end

x

1.6449240668982423

In [110]:
# This can avoud using break end

x=0
iter = 0
while ( iter == 0 || abs(term) < 1e-10) && (iter < 100000)
    term = (1/k)^2
    x = x + term
    iter = iter + 1
end

LoadError: UndefVarError: term not defined

In [114]:
numbers = randn(100)
sum = 0
for k in numbers
    if (k==0) continue end
    sum = sum + 1/k
end

# avoid summing 1/0, as that would result in Inf

LoadError: cannot assign a value to variable Base.sum from module Main

In [117]:
# avoid using continue
numbers = randn(100)
sum = 0
for k in numbers
    if (k != 0)
        sum = sum + 1/k
    end
end


LoadError: cannot assign a value to variable Base.sum from module Main

### While loop

In [115]:
k=0
while k<11
    k=k+1
end

In [116]:
k=0
while k<11
    k=k+1
    print("k=", k, " ")
end

k=1 k=2 k=3 k=4 k=5 k=6 k=7 k=8 k=9 k=10 k=11 

## Functions

### Defining a function

 $\zeta(s)=\sum_{n=1}^\infty 1/n^s$
 
 
 $Riemann  Zeta  function$

In [21]:
function sum_zeta(s,nterms)
    x=0
    for n in 1:nterms
        x=x+(1/n)^s
    end
    return x
end

sum_zeta (generic function with 1 method)

In [22]:
sum_zeta(2,100000)

1.6449240668982423

### One-line functions

In [23]:
sum_zeta(s, nterms)=sum(1/n^s for n=1:nterms)

sum_zeta (generic function with 1 method)

In [24]:
sum_zeta(2,100000)

1.6449240668982423

In [25]:
f(x)=1+x^2  #exactly the math expression

f (generic function with 1 method)

In [26]:
f(3)

10

In [27]:
function f(x)
    return 1+x^2
end

f (generic function with 1 method)

###  Functions with optional and keyword arguments

In [124]:
# optional arguments: nterms=10000

sum_zeta(s, nterms=10000) = sum(1/n^s for n=1:nterms)

sum_zeta(2)  # returns 1.6449240668982423

1.6448340718480652

To make things even easier for the caller, 

a function can be designed to accept arguments 

which are identified by name rather than their position. 

Such arguments are known as keyword arguments, 

and their syntax is very similar to optional arguments, 

the only difference being that they are placed after a semicolon in the function definition.

In the present example, we could make nterms a keyword argument:

In [125]:
# keyword arguments

sum_zeta(s; nterms=10000) = sum(1/n^s for n=1:nterms)

sum_zeta(2)  # returns 1.6449240668982423
sum_zeta(2, nterms = 1e6)  # returns 1.64493306684877

1.64493306684877

### Functions with multiple outputs

In [127]:
function circle(r)
    area = π * r^2
    circumference = 2π * r
    return area, circumference
end

a, c = circle(1.5) #returning a tuple (tuple is immutable)

(7.0685834705770345, 9.42477796076938)

In [128]:
shape = circle(1.5)     # returns (7.0685834705770345, 2.356194490192345)
shape[1]                # 7.0685834705770345
shape[2]                # 2.356194490192345
a, c = shape            # destructures the tuple as in the original

(7.0685834705770345, 9.42477796076938)

### Functions which modify their input (! notation)



In [130]:
function add_one!(x)
    x .= x .+ 1
end

x = [1,2,3]
add_one!(x);    # x is now [2,3,4]



not every type of variable can modified by a function

when passed as an input: the variable has to be mutable. 

For example, Arrays are mutable

###  Anonymous functions

In [133]:
#the following code finds the root of a given function f

function secant(f,a,b,rtol,maxIters)
    iter = 0
    while abs(b-a) > rtol*abs(b) && iter < maxIters
        c,a = a,b
        b = b + (b-c)/(f(c)/f(b)-1)
        iter = iter + 1
    end
    return b
end

secant (generic function with 1 method)

In [134]:
φ = secant( x-> x^2 - x - 1, 1, 2, 1e-15, 10 )

1.6180339887498947

### Storing and calling functions in a separate file

In order to put our functions in a separate file, 

we first create a new `myFunctions.jl` file, 

where we only add our functions:

In [137]:
function sum_series(n)
    x = 0
    for k in 1:n
        x = x + (1/k)^2
    end
    return x
end



sum_series (generic function with 1 method)

then we can call this from another file by using the `include` keyword.

In [138]:
include("myFunctions.jl")

sum_series (generic function with 1 method)

we have another file called `test_myFunctions.jl`

with the following content:

In [140]:
include("myFunctions.jl")
x = sum_series(100000)

1.6449240668982423

then we can call the file `test_myFunctions.jl` as well.

In [139]:
include("test_myFunctions.jl")

1.6449240668982423

## Arrays, Vectors and Matrices

### Direct Input

In [28]:
A=[1 2 3; 1 2 4; 2 2 2 ]

3×3 Matrix{Int64}:
 1  2  3
 1  2  4
 2  2  2

In [29]:
A=[1 2 3;
   1 2 4;
   2 2 2]

3×3 Matrix{Int64}:
 1  2  3
 1  2  4
 2  2  2

In [31]:
A=[1 2 3
   1 2 4
   2 2 2]

3×3 Matrix{Int64}:
 1  2  3
 1  2  4
 2  2  2

In [30]:
b1=[4.0, 5, 6] #3-elt vector
b1=[4.0; 5; 6] #3-elt vector
m1=[4.0 5 6]   #1x3 matrix

1×3 Matrix{Float64}:
 4.0  5.0  6.0

In [1]:
A=["Hello", 1, 2, 3]

4-element Vector{Any}:
  "Hello"
 1
 2
 3

## Array Comprehensions

In [32]:
v=[1/n^2 for n=1:100000]
x=sum(v)

1.6449240668982281

In [33]:
v=[1 4 9 16]

1×4 Matrix{Int64}:
 1  4  9  16

When using parenthesis instead of the square brackets, 

Julia will produce a slightly different object: 

a generator. 

Generators can be iterated to produce the required values when needed.



In [2]:
gen = (1/n^2 for n=1:100000)
x = sum(gen)

1.6449240668982423

### Undefined (undef) Arrays

In [3]:
n = 5
A1 = Array{Float64}(undef,n,n)          # 5×5 Matrix{Float64}
A2 = Matrix{Float64}(undef,n,n)         # 5×5 Matrix{Float64}

V1 = Array{Float64}(undef,n)            # 5-element Vector{Float64}
V2 = Vector{Float64}(undef,n)           # 5-element Vector{Float64}


5-element Vector{Float64}:
 2.2421727692e-314
 2.242172785e-314
 2.242172801e-314
 2.2421728167e-314
 2.242874801e-314

In [4]:
A = Array{String}(undef,n)
A = Array{Any}(undef,n)

5-element Vector{Any}:
 #undef
 #undef
 #undef
 #undef
 #undef

### Empty Arrays

In [5]:
v = Array{Float64}(undef,0)

#equivalently
v = Float64[]

Float64[]

In [7]:
v = []    
# Same as Any[], and you can't change this type easily later (gotcha!)

Any[]

### Initializing Special Kind of Arrays

In [9]:
A = zeros(8,9)
B = ones(8,9)

8×9 Matrix{Float64}:
 1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0

In [10]:
C = rand(6,6)

6×6 Matrix{Float64}:
 0.374532    0.935627   0.333787   0.129198  0.511899   0.433578
 0.00663131  0.975375   0.0974613  0.324806  0.998135   0.230685
 0.116451    0.408779   0.0168342  0.522805  0.468803   0.820298
 0.891309    0.240661   0.288815   0.58787   0.0368627  0.679665
 0.811252    0.0128873  0.168234   0.849058  0.946258   0.352248
 0.418045    0.515145   0.0752789  0.470108  0.60111    0.665447

In [16]:
using LinearAlgebra
M = 5I + rand(2,2)  # I is identity matrix



2×2 Matrix{Float64}:
 5.96519   0.885278
 0.745939  5.82005

reshape(A, dims): 

Create an array with the same data as the given array, but with different dimensions. 

An implementation for a particular type of array may choose whether the data is copied or shared.

In [17]:
v=[m^2 for m=1:4]

4-element Vector{Int64}:
  1
  4
  9
 16

In [18]:
reshape(v, length(v),1)

4×1 Matrix{Int64}:
  1
  4
  9
 16

### Arrays Functions and the Dot Operator

In [38]:
v=[m^2 for m=1:4]

4-element Vector{Int64}:
  1
  4
  9
 16

In [36]:
f(x)=1+x^2
f(3)

10

In [40]:
# f(v) will result in error

In [41]:
f.(v) # use the dot operator to do component-wise operations

4-element Vector{Int64}:
   2
  17
  82
 257

In [19]:
f(x)=3x^3/(1+x^2)
x=[2π/n for n=1:30]
y=f.(x)

30-element Vector{Float64}:
 18.383886633134814
  8.55770151410267
  5.11671431742654
  3.353333929033819
  2.3082162000107957
  1.6431863658206738
  1.2015046969739323
  0.8989201052199165
  0.6862922515493683
  0.5335238620487099
  0.4215523758362779
  0.3379828220140857
  0.27457210010524075
  ⋮
  0.09779758771871808
  0.08466293343637193
  0.07375096045763396
  0.0646159000414539
  0.056913991216668146
  0.05037752063018935
  0.0447960758761785
  0.04000285371284216
  0.035864552856086473
  0.03227383743757451
  0.029143663711431032
  0.026402970924539096

In [20]:
y=sin.(x)

30-element Vector{Float64}:
 -2.4492935982947064e-16
  1.2246467991473532e-16
  0.8660254037844387
  1.0
  0.9510565162951535
  0.8660254037844386
  0.7818314824680298
  0.7071067811865475
  0.6427876096865393
  0.5877852522924731
  0.5406408174555976
  0.49999999999999994
  0.4647231720437685
  ⋮
  0.32469946920468346
  0.3090169943749474
  0.2947551744109042
  0.28173255684142967
  0.2697967711570243
  0.25881904510252074
  0.2486898871648548
  0.23931566428755774
  0.23061587074244017
  0.2225209339563144
  0.21497044021102407
  0.20791169081775931

In [21]:
y=2x.^2+3x.^5-2x.^8

#equivalently
y = @. 2x^2 + 3x^5 - 2x^8

30-element Vector{Float64}:
     -4.828671033653536e6
 -18039.263768983117
   -610.7857528421777
    -40.50500091388652
      0.12239075156841928
      3.0788623155395416
      2.5165970179806223
      1.8406756088311296
      1.3594357907060943
      1.0347659706787375
      0.812285884726568
      0.6550760528496817
      0.5403678534183181
      ⋮
      0.23029553231945027
      0.20638290794502417
      0.1861052313390679
      0.16874585207464307
      0.15375911701431397
      0.14072317776024484
      0.12930739401638117
      0.1192493881563927
      0.11033861036842828
      0.10240437795375669
      0.09530704253783058
      0.08893137900051265

### Array Indexing and Slicing

In [25]:
#Getting the First and Last Elements of an Array
A = rand(6)
A[begin]
A[end]

0.6550600885623967

In [26]:
#Array slicing

A = rand(6,6)                   # 6×6 Matrix{Float64}
B = A[begin:2:end,begin:2:end]  # 3×3 Matrix{Float64}
C = A[1:2:5,1:2:5]              # Same as B


#extract the odd indices in both dimensions from a 6x6 matrix

3×3 Matrix{Float64}:
 0.546931  0.437958  0.136723
 0.267931  0.906242  0.930061
 0.405945  0.139214  0.880401

In [39]:
#Logical Indexing

A = rand(6,6)
A[ A .< 0.5 ] .= 0

14-element view(::Vector{Float64}, [4, 11, 13, 14, 15, 16, 18, 20, 23, 24, 25, 26, 27, 36]) with eltype Float64:
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0

In [43]:
#Iterating over an Array

A = rand(6)

for i ∈ eachindex(A)
    println(string("i=$(i) A[i]=$(A[i])"))
end

i=1 A[i]=0.9396607664183484
i=2 A[i]=0.06519835134888474
i=3 A[i]=0.5194982688443012
i=4 A[i]=0.5646422721796814
i=5 A[i]=0.3165955046362062
i=6 A[i]=0.8746148965351791


In [44]:
A = rand(6,6)
for i ∈ 1:size(A,1), j ∈ 1:size(A,2)
    println(string("i=$(i) j=$(j) A[i,j]=$(A[i,j])"))
end


i=1 j=1 A[i,j]=0.7589050316671616
i=1 j=2 A[i,j]=0.2715284440568917
i=1 j=3 A[i,j]=0.08046459458857358
i=1 j=4 A[i,j]=0.1874029352919171
i=1 j=5 A[i,j]=0.11548720496227072
i=1 j=6 A[i,j]=0.28524058796665386
i=2 j=1 A[i,j]=0.7918079393396654
i=2 j=2 A[i,j]=0.994804200492013
i=2 j=3 A[i,j]=0.8570134533731139
i=2 j=4 A[i,j]=0.7887167835402186
i=2 j=5 A[i,j]=0.8693429546121599
i=2 j=6 A[i,j]=0.20764182342502036
i=3 j=1 A[i,j]=0.1789378017744615
i=3 j=2 A[i,j]=0.6348187869159236
i=3 j=3 A[i,j]=0.4079413875412127
i=3 j=4 A[i,j]=0.33869734560543685
i=3 j=5 A[i,j]=0.7903684288930819
i=3 j=6 A[i,j]=0.99569100667861
i=4 j=1 A[i,j]=0.2859057732224768
i=4 j=2 A[i,j]=0.7108309731033983
i=4 j=3 A[i,j]=0.42387365349689154
i=4 j=4 A[i,j]=0.2873249618061282
i=4 j=5 A[i,j]=0.033734317058262575
i=4 j=6 A[i,j]=0.43359140627338444
i=5 j=1 A[i,j]=0.839888955590691
i=5 j=2 A[i,j]=0.5588561327741542
i=5 j=3 A[i,j]=0.9302212347361206
i=5 j=4 A[i,j]=0.9544408076707857
i=5 j=5 A[i,j]=0.9568394275093488
i=5 j=6 A

In [45]:
A = rand(6,6)
for i ∈ axes(A,1), j ∈ axes(A,2)
    println(string("i=$(i) j=$(j) A[i,j]=$(A[i,j])"))
end

i=1 j=1 A[i,j]=0.946929154710519
i=1 j=2 A[i,j]=0.5392428660948878
i=1 j=3 A[i,j]=0.06929211708383087
i=1 j=4 A[i,j]=0.41952862330883656
i=1 j=5 A[i,j]=0.7561952988939874
i=1 j=6 A[i,j]=0.7611772324103708
i=2 j=1 A[i,j]=0.5942050170335118
i=2 j=2 A[i,j]=0.9095290933474657
i=2 j=3 A[i,j]=0.9724581073247426
i=2 j=4 A[i,j]=0.3251550838952696
i=2 j=5 A[i,j]=0.6547646038482829
i=2 j=6 A[i,j]=0.6115211551345126
i=3 j=1 A[i,j]=0.6890959016399616
i=3 j=2 A[i,j]=0.2801898492084315
i=3 j=3 A[i,j]=0.5287606198333604
i=3 j=4 A[i,j]=0.9392166904363235
i=3 j=5 A[i,j]=0.5291064438603276
i=3 j=6 A[i,j]=0.5067635913543151
i=4 j=1 A[i,j]=0.8878342925169779
i=4 j=2 A[i,j]=0.5060978291500887
i=4 j=3 A[i,j]=0.5695655050528173
i=4 j=4 A[i,j]=0.8942749359637817
i=4 j=5 A[i,j]=0.7739665838829417
i=4 j=6 A[i,j]=0.5209437260881647
i=5 j=1 A[i,j]=0.558884580515848
i=5 j=2 A[i,j]=0.49527066317499946
i=5 j=3 A[i,j]=0.3580310634153947
i=5 j=4 A[i,j]=0.7446024240739765
i=5 j=5 A[i,j]=0.5599012344063413
i=5 j=6 A[i,j

- `firstindex(A,dim)`
- `lastindex(A,dim)`
- `similar(Array{Float64}, axes(A))` to allocate an array with the same indices as A.

### Array Operations

In [59]:
A=[1 2
   3 4]
B=[0.1 0.2
   0.3 0.4]

2×2 Matrix{Float64}:
 0.1  0.2
 0.3  0.4

In [45]:
A*B

2×2 Matrix{Float64}:
 0.7  1.0
 1.5  2.2

In [46]:
A.*B # elt-wise operations

2×2 Matrix{Float64}:
 0.1  0.4
 0.9  1.6

In [52]:
# dot product

v=rand(1000)
w=rand(1000)
z=dot(v,w)

#equivalently
z=v'w

252.27145329935905

1xN matrices are not the same as N-element vectors.

In [60]:
b1 = [4.0, 5, 6]                # 3-element Vector{Float64}
b2 = [4.0; 5; 6]                # 3-element Vector{Float64}
m1 = [4.0 5 6]                  # 1×3 Matrix{Float64}

x=A\b1                          # Solves A*x=b
x=A\b2                          # Solves A*x=b  
# x=A\m1                          # Error!!

LoadError: DimensionMismatch("arguments must have the same number of rows")

### Resizing and Concatenating Arrays

In [62]:
A = Float64[]       # Equivalent to A=Array{Float64}(undef,0)
push!(A, 4)         # Adds the number 4 at the end of the array
push!(A, 3)         # Adds the number 3 at the end of the array
v = pop!(A)         # Returns 3 and removes it from A

3.0

`pushfirst!`, and `popfirst!` which work on the beginning of the array 

as opposed to the end. 

Additionally, the function `splice!(A,i)` and `deleteat!(A,i)` 

will incorporates (resp. delete) an element at a given position i.



we can resort to `hcat`, `vcat`, and `cat` functions, 

to concatenate in the horizontal, vertical, 

or along any given dimension.

In [63]:
A = [4 5 6] 
B = [6 7 8] 

M1 = vcat(A, B)


M2 = hcat(A, B)


1×6 Matrix{Int64}:
 4  5  6  6  7  8

In [64]:
M1 = cat(A, B, dims=1)
M2 = cat(A, B, dims=2)
M3 = cat(A, B, dims=3)

1×3×2 Array{Int64, 3}:
[:, :, 1] =
 4  5  6

[:, :, 2] =
 6  7  8

In [67]:
### Concatenating Matrices

M1 = [A; B]

M2 = [A B]

1×6 Matrix{Int64}:
 4  5  6  6  7  8

## Data Structures