# vector_matrix_array

- An arrays in Julia is a collection of elts.
- 1Darray: vector (1 index for size)
- 2Darray: matrix (2 indicies for size)
- n-D array: this is possible too

In [2]:
a1=[1,2,3] # a vector
size(a1)

(3,)

In [5]:
a2=[1;2;3] # the same vector
size(a2)

(3,)

In [6]:
a1==a2

true

In [7]:
a3=reshape(a1, length(a1), 1) #convert vector to matrix
#reshape(vector, row, col)

size(a3)

(3, 1)

In [8]:
a1==a3 #not equal, b/c one is vector, another is matrix

false

In [9]:
b1=(1,2,3)
size(b1) #doesn't work for tuple

LoadError: MethodError: no method matching size(::Tuple{Int64, Int64, Int64})
Closest candidates are:
  size(::Tuple, ::Integer) at /Applications/Julia-1.7.app/Contents/Resources/julia/share/julia/base/tuple.jl:27
  size(::Union{LinearAlgebra.Adjoint{T, var"#s859"}, LinearAlgebra.Transpose{T, var"#s859"}} where {T, var"#s859"<:(AbstractVector)}) at /Applications/Julia-1.7.app/Contents/Resources/julia/share/julia/stdlib/v1.7/LinearAlgebra/src/adjtrans.jl:172
  size(::Union{LinearAlgebra.Adjoint{T, var"#s859"}, LinearAlgebra.Transpose{T, var"#s859"}} where {T, var"#s859"<:(AbstractMatrix)}) at /Applications/Julia-1.7.app/Contents/Resources/julia/share/julia/stdlib/v1.7/LinearAlgebra/src/adjtrans.jl:173
  ...

In [10]:
a4=[1 2 
    3 4]  # 2x2 matrix

size(a4)

(2, 2)

In [13]:
a4′=[1 2 ; 3 4]
size(a4′)   # \prime + TAB

(2, 2)

In [14]:
a4==a4′

true

# basic operations for arrays

In [17]:
1+a1 #doen't work

LoadError: MethodError: no method matching +(::Int64, ::Vector{Int64})
For element-wise addition, use broadcasting with dot syntax: scalar .+ array
Closest candidates are:
  +(::Any, ::Any, ::Any, ::Any...) at /Applications/Julia-1.7.app/Contents/Resources/julia/share/julia/base/operators.jl:655
  +(::T, ::T) where T<:Union{Int128, Int16, Int32, Int64, Int8, UInt128, UInt16, UInt32, UInt64, UInt8} at /Applications/Julia-1.7.app/Contents/Resources/julia/share/julia/base/int.jl:87
  +(::Union{Int16, Int32, Int64, Int8}, ::BigInt) at /Applications/Julia-1.7.app/Contents/Resources/julia/share/julia/base/gmp.jl:535
  ...

In [18]:
1 .+a1  # work, elt by elt

3-element Vector{Int64}:
 2
 3
 4

In [19]:
1.+ a1 # doesn't work

LoadError: syntax: invalid syntax "1.+"; add space(s) to clarify

In [20]:
a1 + a2  # work, b/c dim match

3-element Vector{Int64}:
 2
 4
 6

In [21]:
a1 .+ a2

3-element Vector{Int64}:
 2
 4
 6

# about random numbers

In [22]:
c1=rand(3) # a vector of 3 random numbers

3-element Vector{Float64}:
 0.17852189751082337
 0.4283667578011102
 0.03672088438190346

In [23]:
c2=rand(3,1) # a 3x1 matrix

3×1 Matrix{Float64}:
 0.5897732139932872
 0.5440733114525008
 0.5107275645795162

In [26]:
using Random
c3= rand(Xoshiro(12), 3) #vector
c4= rand(Xoshiro(12), 3,1) # martix

@show c3   
@show c4

c3 = [0.32018269515620323, 0.938582363311554, 0.5501748910470424]
c4 = [0.32018269515620323; 0.938582363311554; 0.5501748910470424;;]


3×1 Matrix{Float64}:
 0.32018269515620323
 0.938582363311554
 0.5501748910470424

In [25]:
c3==c4 #c3 c4 look the same; but different data type

false

- Many Julia fcns are type-dependent
- Some fcns accpet vectors, some accept matrix
- Incorrect types may result in errors

# About Function

In [28]:
using Random

In [29]:
function test1()
    display("I love the class!")
end

test1()

"I love the class!"

## function with return

In [33]:
function test2()
    vec1 = rand(3)  # U(0,1)
    vec2 = vec1*2   # U(0,2)
    vec3=vec2 .- 1  # U(-1,1)
    return vec3
end

res = test2()

3-element Vector{Float64}:
 0.43099004788742246
 0.7915918214761433
 0.8189843197384166

## adding options

In [34]:
function test3(N=1, a=1, b=1)
    vec1 = rand(N)    # U(0,1)
    vec2 = vec1*a     # U(0,2)
    vec3 = vec2 .- b  # U(-1,1)
    return vec3
end


res = test3(3,2,1)
res = test3() # use default value

1-element Vector{Float64}:
 -0.7241685779655845

- See if the mean is expected

In [35]:
using Statistics
res1 = test3(10000, 2, 1)
@show mean(res1)

mean(res1) = 0.0007484560937989949


0.0007484560937989949

- making options more intuitive
- `;`之前看位置 `;`之後看名稱

In [36]:
test3(N=3, 2, 1) # doesn't work

LoadError: MethodError: no method matching test3(::Int64, ::Int64; N=3)
Closest candidates are:
  test3(::Any, ::Any) at In[34]:1 got unsupported keyword argument "N"
  test3(::Any, ::Any, ::Any) at In[34]:1 got unsupported keyword argument "N"
  test3(::Any) at In[34]:1 got unsupported keyword argument "N"

In [44]:
# `;`之前看位置 `;`之後看名稱


function test4(; N=1, a=1, b=1) #named keyword
    vec1 = rand(N)     # U(0,1)
    vec2 = vec1*a      # U(0,2)
    vec3 = vec2 .- b   # U(-1,1)
    return vec3
end

test4 (generic function with 1 method)

In [43]:
test4(N=3, a=2, b=1)

test4(a=2,N=3, b=1)  #switch position is ok

3-element Vector{Float64}:
  0.1430217914557499
 -0.4566519747134752
 -0.8397657787785096

## a mix of styles

In [45]:
function test5(N=1; a=1, b=1) 
    vec1 = rand(N)     # U(0,1)
    vec2 = vec1*a      # U(0,2)
    vec3 = vec2 .- b   # U(-1,1)
    return vec3
end

test5 (generic function with 2 methods)

In [46]:
test5(3,a=2, b=-1)

3-element Vector{Float64}:
 2.649364623563736
 1.8781792742071686
 1.0423362364579771

In [47]:
test5(3,b=1, a=2)

3-element Vector{Float64}:
 -0.1250176587483216
  0.3636202074785002
  0.8231079581388612

In [49]:
test5(N=3, a=2, b=-1) # doesn't work

LoadError: MethodError: no method matching test5(::Int64; N=3, a=2, b=-1)
Closest candidates are:
  test5(::Any; a, b) at In[45]:1 got unsupported keyword argument "N"
  test5() at In[45]:1 got unsupported keyword arguments "N", "a", "b"

In [50]:
test5(a=2, 5, b=1) # works too!

5-element Vector{Float64}:
 -0.6124698621432823
 -0.96289332277869
 -0.436752951115019
  0.9288318951954107
  0.8378394545230923

## add option types

In [51]:
# 指定option type

function test4a(; N:: Integer=1, a:: Float64=1, b=-1)
    vec1 = rand(N)     # U(0,1)
    vec2 = vec1*a      # U(0,2)
    vec3 = vec2 .- b   # U(-1,1)
    return vec3
end

test4a (generic function with 1 method)

In [52]:
test4a(N=3.0, a=2, b=-1) # doesn't work b/c N

LoadError: TypeError: in keyword argument N, expected Integer, got a value of type Float64

In [55]:
test4a(N=3, a=2, b=1) #doesn't work b/c a

LoadError: TypeError: in keyword argument a, expected Float64, got a value of type Int64

In [54]:
test4a(N=3, a=2.0, b=1) # work

3-element Vector{Float64}:
 -0.339931726883407
 -0.5169648467286829
  0.38570334225601877

In [56]:
test4a(N=3, a=2.0, b=[1,2,3])  # work b/c dimension match

3-element Vector{Float64}:
  0.6341716568710016
 -1.8976496484886032
 -2.515046129125719

In [57]:
test4a(N=3, a=2.0, b=[1,2]) #doesn't work

LoadError: DimensionMismatch("arrays could not be broadcast to a common size; got a dimension with lengths 3 and 2")

## with multiple outputs

In [58]:
function test6(; N=1, a=1, b=1) #named keyword
    vec1 = rand(N)     # U(0,1)
    vec2 = vec1*a      # U(0,2)
    vec3 = vec2 .- b   # U(-1,1)
    return N, vec3
end


test6 (generic function with 1 method)

In [59]:
res= test6(N=3, a=2, b=1)
@show res;
@show res[1];
@show res[2];


res = (3, [0.39975194028316086, -0.8878942764937812, -0.026749913195704078])
res[1] = 3
res[2] = [0.39975194028316086, -0.8878942764937812, -0.026749913195704078]


In [60]:
res1, res2= test6(N=2, a=2, b=-1)
@show res1
@show res2

res1 = 2
res2 = [1.7041417064442, 2.805123508389161]


2-element Vector{Float64}:
 1.7041417064442
 2.805123508389161

## funciton with struct

- 相當於python中的class

In [61]:
struct myData
    x #field 1
    y #field 2
end

In [62]:
function test7(; N=1, a=1, b=1) #named keyword\
    vec1 = rand(N)     # U(0,1)
    vec2 = vec1*a      # U(0,2)
    vec3 = vec2 .- b   # U(-1,1)
    return myData(vec2, vec3)
end



test7 (generic function with 1 method)

In [65]:
res= test7(N=3, a=2, b=-1)


@show res;
@show res.x;
@show res.y;

res = myData([1.7490244438539473, 1.7431758394211587, 0.8258361046262961], [2.7490244438539473, 2.7431758394211587, 1.825836104626296])
res.x = [1.7490244438539473, 1.7431758394211587, 0.8258361046262961]
res.y = [2.7490244438539473, 2.7431758394211587, 1.825836104626296]


## struct also has types

In [69]:
struct myData4
    x::Int
    y::Vector
end

In [70]:
function test8(; N=1, a=1, b=1) #named keyword
    vec1 = rand(N)     # U(0,1)
    vec2 = vec1*a      # U(0,2)
    vec3 = vec2 .- b   # U(-1,1)
    return myData4(vec2, vec3)
end

test8 (generic function with 1 method)

In [72]:
test8(N=3, a=2, b=1)  # error b/c not Int

LoadError: MethodError: Cannot `convert` an object of type Vector{Float64} to an object of type Int64
Closest candidates are:
  convert(::Type{T}, ::Ptr) where T<:Integer at /Applications/Julia-1.7.app/Contents/Resources/julia/share/julia/base/pointer.jl:23
  convert(::Type{T}, ::T) where T<:Number at /Applications/Julia-1.7.app/Contents/Resources/julia/share/julia/base/number.jl:6
  convert(::Type{T}, ::Number) where T<:Number at /Applications/Julia-1.7.app/Contents/Resources/julia/share/julia/base/number.jl:7
  ...