## 向量

In [1]:
v1=[2,3,5,7,11,13,17]
v2=[1.5,3,4,9.12]
v3=["apple","orange","banana"]
v4=[123,3.14,"math","[1,2,3]"]

4-element Vector{Any}:
 123
   3.14
    "math"
    "[1,2,3]"

In [2]:
length(v1)

7

In [3]:
1:2:7

1:2:7

In [4]:
5:-1:1

5:-1:1

In [5]:
#collect()函数可以将范围转换成向量
collect(5:-1:1)

5-element Vector{Int64}:
 5
 4
 3
 2
 1

In [7]:
v1=[2,3,5,7,11,13,17]
v1[2]

3

In [8]:
v1[end]

17

In [9]:
v1[begin]

2

In [10]:
v1[2]=0
@show v1;

v1 = [2, 0, 5, 7, 11, 13, 17]


`@show expr`可以用比较简洁的带有提示的方式显示表达式和表达式的值。

In [11]:
v1=[2,3,5,7,11,13,17]
v1[2:4]

3-element Vector{Int64}:
 3
 5
 7

In [12]:
v1[4:end]

4-element Vector{Int64}:
  7
 11
 13
 17

In [13]:
v1[1:(end-3)]

4-element Vector{Int64}:
 2
 3
 5
 7

In [14]:
v1[1:2:7]

4-element Vector{Int64}:
  2
  5
 11
 17

In [16]:
v1[end:-1:1]

7-element Vector{Int64}:
 17
 13
 11
  7
  5
  3
  2

`reverse(x)`可以返回次序颠倒后的数组。

In [18]:
v1=[2,3,5,7,11,13,17]
v1[:].=0
@show v1;

v1 = [0, 0, 0, 0, 0, 0, 0]


In [19]:
v1=[2,3,5,7,11,13,17]
v1[1:3].=0
@show v1;

v1 = [0, 0, 0, 7, 11, 13, 17]


In [21]:
v1 = [2, 3, 5, 7, 11, 13, 17]
v1[1:3] = [101, 303, 505]; 
@show v1;


v1 = [101, 303, 505, 7, 11, 13, 17]


## Data type

元素都是整数时， 显示其类型为“Array{Int64}”， 常用的还有“Array{Float64}”， “Array{String}”， “Array{Any}”等， “Any”是Julia语言类型系统的根类型， 相应的数组可以容纳任何Julia对象作为元素。

如果数组元素都是基本类型如Float64， 则不允许给元素赋值为其它类型

In [22]:
vf=[1.2, 2.5, 3.6]; vf

3-element Vector{Float64}:
 1.2
 2.5
 3.6

In [24]:
vf[2]="abc"

LoadError: MethodError: Cannot `convert` an object of type String to an object of type Float64
Closest candidates are:
  convert(::Type{T}, ::T) where T<:Number at /Applications/Julia-1.7.app/Contents/Resources/julia/share/julia/base/number.jl:6
  convert(::Type{T}, ::Number) where T<:Number at /Applications/Julia-1.7.app/Contents/Resources/julia/share/julia/base/number.jl:7
  convert(::Type{T}, ::Base.TwicePrecision) where T<:Number at /Applications/Julia-1.7.app/Contents/Resources/julia/share/julia/base/twiceprecision.jl:262
  ...

In [25]:
eltype(vf) #elt type

Float64

## initialize vector

`zeros(n)`可以生成元素类型为Float64、元素值为0、长度为n的向量

In [26]:
zeros(3)

3-element Vector{Float64}:
 0.0
 0.0
 0.0

`zeros(Int64, 3)`可以生成指定类型的（这里是Int64）初始化向量

In [27]:
zeros(Int64,3)

3-element Vector{Int64}:
 0
 0
 0

用`Vector{Float64}(undef, n)`可以生成元素类型为Float64的长度为n的向量， 元素值未初始化，如

In [6]:
Vector{Float64}(undef,3)

3-element Vector{Float64}:
 5.0e-324
 0.0
 1.5e-323

In [11]:
y1 = Vector{Int}(undef, 3);

可以用`fill!()`填入统一的值。

函数名以!结尾是一个习惯用法， 表示该函数会修改其第一自变量的值。

In [33]:
fill!(y1,100)

3-element Vector{Int64}:
 100
 100
 100

可以用`fill(value, n)`生成一个元素值都等于value的长度为n的一维数组。

可以用`collect()`将一个范围转换成可修改的向量

In [34]:
collect(1:5)

5-element Vector{Int64}:
 1
 2
 3
 4
 5

## 变量与值

Julia的变量仅仅是向实际存储空间的引用(reference)， 或称绑定(binding)， 所以两个变量可以引用(绑定)到同一个向量的存储空间， 修改了其中一个变量的元素值，则另一个变量的元素也被修改了。 如

In [35]:
x1=[1,2,3]
x2=x1
x2[2]=100
@show x1;

x1 = [1, 100, 3]


In [ ]:
“===”或“≡”(\equiv+TAB)可以比较两个变量是否同一对象， 如：

In [37]:
x2===x1

true

制作数组的副本， 用`copy()`函数

In [38]:
x1=[1,2,3]
x2=copy(x1)
x2[2]=-100
@show x1;
x2===x1

x1 = [1, 2, 3]


false

In [39]:
x1=[1,2,3]
x2=x1[:]
x2[2]=-100
@show x1;


x1 = [1, 2, 3]


In [41]:
x0=[3,4]
x1=[1,2,x0]
x1[3][1]=333
@show x0;


x0 = [333, 4]


因为x1中引用（绑定）了x0的值， 

所以x1[3]和x0共用同一存储， 修改了x1[3]就修改了x0。 

那么， 制作x1的副本能否解决问题？

In [42]:
x0=[3,4]
x1=[1,2,x0]
x2=copy(x1)
x2[1]=111
x2[3][1]=333

@show x2;
@show x1;
@show x0;

x2 = Any[111, 2, [333, 4]]
x1 = Any[1, 2, [333, 4]]
x0 = [333, 4]


虽然x1[1]没有被修改，但是x1[3][1]还是被修改了， x0也被修改了。 

这是因为copy()执行的是所谓“浅层复制”， 对于内嵌的对象仍为引用。 

可以用deepcopy()， 能解决大部分问题：

In [44]:
x0=[3,4]
x1=[1,2,x0]
x2=deepcopy(x1)
x2[1]=111
x2[3][1]=333
@show x2;
@show x1;
@show x0;

x2 = Any[111, 2, [333, 4]]
x1 = Any[1, 2, [3, 4]]
x0 = [3, 4]


仅修改了x2，没有修改x1和x0。

## 向量的有关函数

函数`indexin(a, b)`返回向量a的每个元素首次出现在b中的位置， 没有时返回nothing，如：



In [45]:
indexin([1,3,5,3],[1,2,3])

4-element Vector{Union{Nothing, Int64}}:
 1
 3
  nothing
 3

In [46]:
1 in [1,3,5,3]

true

若v是向量，x是一个元素， 

push!(v, x)修改向量v， 将x添加到向量v的末尾。 

pushfirst!(v, x)修改向量v， 将x添加到向量v的开头，原有的元素后移。 

注意， 函数名以叹号结尾是一个习惯约定， 表示此函数会修改其第一个自变量。

insert!(v, k, xi)函数可以在向量v的指定下标k位置插入指定的一个元素， 原有的元素后移。

如

In [48]:
v3=[2,3,5]
push!(v3,7)
@show v3;

pushfirst!(v3,1)
@show v3;

v3 = [2, 3, 5, 7]
v3 = [1, 2, 3, 5, 7]


若v是向量，u也是一个向量， 

`append!(v, u)`修改向量v， 将u的所有元素添加到向量v的末尾。 

要注意append!和push!的区别， 一个是添加一个向量的所有元素到末尾， 一个是添加一个元素到末尾。 如

In [49]:
v3=[2,3,5]
append!(v3,[7,11])
@show v3;



v3 = [2, 3, 5, 7, 11]


`replace!()`函数可以用来在数组中替换元素，如：

In [50]:
x=[1,2,1,4,1]
replace!(x,1=>0)
@show x;

x = [0, 2, 0, 4, 0]


In [51]:
x = [1, 2, 1, 4, 1]
replace!(x, 1 => 0, 4 => 3)
@show x;


x = [0, 2, 0, 3, 0]


可以指定一个总替换次数的上限

In [52]:
x = [1, 2, 1, 4, 1]
replace!(x, 1 => 0, 4 => 3, count = 2)
@show x;


x = [0, 2, 0, 4, 1]


如果要合并两个一维数组并将结果生成一个新数组， 不修改原来的两个数组， 可以用`vcat()`函数，如：

In [53]:
v1=[1,2]; v2=[-2,-1]
v3=vcat(v1,v2)
@show v3;


v3 = [1, 2, -2, -1]


In [55]:
v3[1]=111
@show v1;

v1 = [1, 2]


`filter!(f, x)`指定一个示性函数f，将x中不满足条件的元素删除, 如：



In [56]:
x=[2,3,5,7,11,13]
filter!(a-> a%3==1,x)
show(x)

[7, 13]

In [57]:
sqrt.([1,2,3]) # dot operator

3-element Vector{Float64}:
 1.0
 1.4142135623730951
 1.7320508075688772

## tuple

In [58]:
(1,2,3)
(1,"john",5.1)

(1, "john", 5.1)

In [59]:
x=(1,)
typeof(x)

Tuple{Int64}

In [60]:
x=(1)
typeof(x)

Int64

In [62]:
x=("a","b","c","d")
typeof(x)

NTuple{4, String}

In [63]:
x[1]

"a"

In [65]:
x[2:3]

("b", "c")

In [66]:
x[2]="x" #tuple is immutable

LoadError: MethodError: no method matching setindex!(::NTuple{4, String}, ::String, ::Int64)

In [67]:
(1,3,5)<(1,3,6)

true

## 赋值等号左边的元组

In [69]:
a,b =13,17
println("a=",a, " b=", b)


a=13 b=17


In [70]:
a,b =b,a
println("a=",a, " b=",b)

a=17 b=13


In [71]:
a,b =[19,23]
println("a=",a," b=",b)

a=19 b=23


In [72]:
divrem(11,4) #(商，餘)

(2, 3)

用collect()将元组转换为一维数组

In [73]:
collect((1,3,5))

3-element Vector{Int64}:
 1
 3
 5

## 两个向量成对使用

设x和y是两个等长的一维数组， zip(x, y)是一个迭代器（可以用在for循环中），

每次迭代返回两个数组的一对对应元素。 

可以用collect()将迭代器转换成二元组的数组：

In [75]:
x=["a","b","c"]
y=[3,1,2]

@show zip(x,y);
collect(zip(x,y))

zip(x, y) = zip(["a", "b", "c"], [3, 1, 2])


3-element Vector{Tuple{String, Int64}}:
 ("a", 3)
 ("b", 1)
 ("c", 2)

## 有名元组

In [76]:
tn1=(; name="John", age=32)
#有分号使得定义有名元组的意图更明显。

tn1[:name]
#要注意有名元组用变量名访问时用的是符号(Symbol)， 即不写成字符串的变量名前面有冒号。 也可以用加点格式访问：

"John"

In [78]:
tn1.name

"John"

In [77]:
tn1[1]

"John"

## 字典

In [12]:
d=Dict("name"=> "Li Ming", "age"=>18)


Dict{String, Any} with 2 entries:
  "name" => "Li Ming"
  "age"  => 18

In [13]:
d1=Dict() #generate empty dict

Dict{Any, Any}()

In [14]:
# use binary tuple to generate dict
d2orig=[("a",1),("b",2),("c",3),("d",4)]
d2=Dict(d2orig)

Dict{String, Int64} with 4 entries:
  "c" => 3
  "b" => 2
  "a" => 1
  "d" => 4

当键和值分别保存在两个等长的数组中的时候， 

可以用zip()函数将这两个数组合并为二元组的数组， 从而产生字典

In [15]:
x=["a","b","c","d"]
y=[1,2,3,4]
d2=Dict(zip(x,y))

Dict{String, Int64} with 4 entries:
  "c" => 3
  "b" => 2
  "a" => 1
  "d" => 4

In [16]:
length(d2)

4

保险起见， 最好在生成字典时指定键和值的数据类型， 

格式为Dict{S, T}(...)，S为键的类型，T为值的类型。

In [17]:
Dict{Sting,Int64}("apple=>1","pear"=>2,"orange"=>3)

LoadError: UndefVarError: Sting not defined

## Pair

事实上， `"apple" => 1`这样的写法也是Julia的一种数据类型， 称为“对”(Pair)。

In [18]:
x="apple"=>1
typeof(x)

Pair{String, Int64}

In [19]:
first(x) #extract first item from pair

"apple"

In [20]:
last(x) #extract last item from pair

1

In [21]:
(first(x),last(x))

("apple", 1)

In [22]:
collect(d2) #将字典转换成键、值二元组的一维数组

4-element Vector{Pair{String, Int64}}:
 "c" => 3
 "b" => 2
 "a" => 1
 "d" => 4

## 訪問元素

In [23]:
d=Dict("name"=>"Li Ming", "age"=>18)
d["age"]

18

读取字典中单个键的对应值也可以用get(d, key, default)的格式， 

其中default是元素不存在时的返回值

In [24]:
get(d,"age",0)

18

In [25]:
haskey(d,"gender") #has key? chek if this key exist

false

In [26]:
d["gender"]="Male"
@show d;

d = Dict{String, Any}("name" => "Li Ming", "gender" => "Male", "age" => 18)


## 遍歷字典

In [36]:
d2=Dict("a"=>1,"b"=>2,"c"=>3,"d"=>4)

for k in keys(d2)
    println(k,"=>",d2[k])  # no order
end


keys(d2)

c=>3
b=>2
a=>1
d=>4


KeySet for a Dict{String, Int64} with 4 entries. Keys:
  "c"
  "b"
  "a"
  "d"

In [40]:
for k in sort(collect(keys(d2)))
    println(k,"=>",d2[k])  #has order
end

collect(keys(d2))  #用collect()将元组转换为一维数组

a=>1
b=>2
c=>3
d=>4


4-element Vector{String}:
 "c"
 "b"
 "a"
 "d"

In [41]:
collect(values(d2))

4-element Vector{Int64}:
 3
 2
 1
 4

In [49]:
d2p=collect(d2)

sort!(d2p, by=first)


for(k, v) in d2p
    println(k,"==>",v)
end

a==>1
b==>2
c==>3
d==>4


In [38]:
"a" in keys(d2)
"g" ∈ keys(d2)

false

In [50]:
for(k,v ) in d2
    println(k, "=>",v)
end

c=>3
b=>2
a=>1
d=>4


In [52]:
[(k,v) for (k,v) in d2]

4-element Vector{Tuple{String, Int64}}:
 ("c", 3)
 ("b", 2)
 ("a", 1)
 ("d", 4)

## 用生成器生成字典

`Dict(x=>f(x) for x in collection)`

In [53]:
Dict(x=> x*x for x in [2,3,5,7])

Dict{Int64, Int64} with 4 entries:
  5 => 25
  7 => 49
  2 => 4
  3 => 9

## 字典应用：频数表

In [55]:
#get(dict, key, default)

sex=["F","M","M","F","M"]
freqs=Dict()
for xi in sex
    freqs[xi]= get(freqs, xi, 0)+1
end

freqs

Dict{Any, Any} with 2 entries:
  "M" => 3
  "F" => 2

In [56]:
function freqd(x)
    y=Dict()
    for xi in x
        y[xi]=get(y,xi,0)+1
    end
    return y
end
freqd(sex)

Dict{Any, Any} with 2 entries:
  "M" => 3
  "F" => 2

In [61]:
# using Pkg
# Pkg.add("StatsBase")

In [58]:
using StatsBase
StatsBase.countmap(sex)

Dict{String, Int64} with 2 entries:
  "M" => 3
  "F" => 2

In [59]:
function freq(x) 
    y=StatsBase.countmap(x)
    return keys(y), values(y)
end
freq(sex)

(["M", "F"], [3, 2])

In [60]:
d3=freq("disillusionment")

(['n', 'd', 'i', 's', 'l', 'u', 'o', 'm', 'e', 't'], [2, 1, 3, 2, 2, 1, 1, 1, 1, 1])

## Set

In [62]:
Set(1:3)

Set{Int64} with 3 elements:
  2
  3
  1

In [63]:
Set([1,2,3]) #Set(1,2,3) is wrong

Set{Int64} with 3 elements:
  2
  3
  1

In [64]:
Set(["a","b","c","d"])

Set{String} with 4 elements:
  "c"
  "b"
  "a"
  "d"

In [65]:
Set("keep")

Set{Char} with 3 elements:
  'k'
  'e'
  'p'

Set()输入一个序列（字符串也是序列）， 将序列的元素变成集合元素。 

注意Set([1,2,3])正确而Set(1,2,3)错误。

因为字符串也是序列， 所以， 要生成只有一个字符串的集合， 也需要将其作为字符串的数组输入

In [66]:
Set(["keep"])

Set{String} with 1 element:
  "keep"

In [67]:
#判断某个单词的字母都在另一个单词的字母中
Set("cat") ⊆ Set("atomic")

true

In [68]:
#判断某个单词中有没有重复字母：
length(Set("keep"))< length("keep") 

true